config/routes.rb
MeetylDemo::Application.routes.draw do

  resources :pictures
  resources :comments do
    get :display_picture_comments, on: :collection
  end

  root 'pictures#new'

end

app/models/comment.rb
# require 'elasticsearch-api'
# require 'json'
require 'hashie'

class Comment
  include DataMapper::Resource

  property :id, Serial
  property :content, Text

  belongs_to :picture

  after :save, :elastic_index

 def elastic_index
  client = Comment.elastic_client
  client.index  index: 'meetyl-demo', type: 'comment', id: self.id, body: data_to_be_indexed
  end

  def self.get_indexed_comments(picture_id)
    client = elastic_client
    response = client.search index: 'meetyl-demo', type: 'comment', body: { query: { match: { id: picture_id } } }
    mash = Hashie::Mash.new response
    comments_objects = mash.hits.hits.map { |obj| Comment.get(obj['_id'].to_i) }
  end

  def self.elastic_client
    Elasticsearch::Client.new log: true
  end

  def data_to_be_indexed
    # As I understood it from the brief, the data to be indexed should 
    # be the id, title and  description of the picture ( not certain if 
    # I  got that right, but the data to be indexed could easily be 
    # updated in just here)
    picture.to_json(only: [:id, :title, :description])
  end

end

app/models/picture.rb
class Picture
  include DataMapper::Resource
  include DataMapper::Validate
  include Paperclip::Resource
  

  property :id, Serial
  property :title, String
  property :description, String

 has_attached_file :picture_file,
                   :styles => { :large => "1056x408#",
                                :thumb => "333x150#"}
  validates_attachment_presence :picture_file

  has n, :comments


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(params[:comment])
    @picture = @comment.picture
    respond_to do |format|
      if @comment.save
        format.html { redirect_to pictures_path}
        format.js  {}
      end
    end

  end

  def display_picture_comments
    @comments = Comment.get_indexed_comments(params[:picture_id]).to_json
    respond_to do |format|
        format.js  
      end
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :get_picture, only: :show

  def new
    @picture = Picture.new
  end


  def create
    @picture = Picture.new(params[:picture])
    if @picture.save
      redirect_to pictures_path
    else
      render :new
    end
  end


  # def edit
  # end


  # def update
  #   @picture.update(params[:picture])
  #   redirect_to edit_picture_path(@picture)
  # end

  def index
    @pictures = Picture.all.page(params[:page]).per(6)
  end


  def show
    @comment = Comment.new
    @picture.comments << @comment
  end


  def destroy
    @picture.destroy
    redirect_to action: :index
  end

  private

  def get_picture
    @picture = Picture.get(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def show_title(picture)
    picture.title ||= 'No Title'
  end

  def show_description(picture)
    picture.description ||= 'No Description'
  end

end

app/views/comments/_form.html.haml
#comment_form
  = simple_form_for @comment, :remote => true do |f|
    %ul
      = f.input :content
      = f.input :picture_id, :as => :hidden
    = f.submit :class => 'submit'

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.haml

app/views/comments/display_picture_comments.js.erb
$('#comment_created').remove();
$('#img').after('<h3>Comments</h3><ul id="comments_list"></ul>');
$(<%= raw @comments %>).each(function(){
  $('#comments_list').append('<li>' + this.content + '</li>');
  })
$('#comments_link').remove()

app/views/comments/new.html.haml
%h1 Comments#new
%p Find me in app/views/comments/new.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MeetylDemo
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header.navigation
      .menu-wrapper
        %a.logo{href: "javascript:void(0)"}
          %img{alt: "", src: "https://raw.github.com/Magnus-G/Random/master/placeholder_logo_1.png"}/
        %p#js-mobile-menu.navigation-menu-button MENU
        .nav
          %ul#navigation-menu
            %li.nav-link
              = link_to "All Pictures", pictures_path
            %li.nav-link
              = link_to "New Picture", new_picture_path

    = yield

app/views/pictures/_form.html.haml
= simple_form_for @picture do |f|
  %ul
    = f.input :title
    = f.input :description
    = f.input :picture_file
  = f.submit :class => 'submit'

app/views/pictures/_picture.html.haml
=  content_tag_for(:div, picture, :class => 'card') do
  
  = link_to picture_path(picture) do
    .card-image
      - if picture.picture_file?
        = image_tag picture.picture_file.url(:thumb)
    .card-header
      = show_title(picture)
    .card-copy
      = show_description(picture)

app/views/pictures/create.html.haml
%h1 Pictures#create
%p Find me in app/views/pictures/create.html.haml

app/views/pictures/index.html.haml
.refill
  .refills-wrapper
    .line-behind-text
      %h6.er_toc_tag
        All Pictures
    .cards
      = render @pictures 
    = paginate @pictures

app/views/pictures/new.html.haml
.refill
  .refills-wrapper
    .line-behind-text
      %h6.er_toc_tag
        New Picture

    = render 'form'

app/views/pictures/show.html.haml
.refill
  .refills-wrapper
    .line-behind-text
      %h6.er_toc_tag
        = show_title(@picture)
    .hero-copy
      %h1 
        = show_title(@picture)
      %p 
        = show_description(@picture)
    #img
      = image_tag @picture.picture_file.url(:large)


    %p
      = link_to 'Show Comments', display_picture_comments_comments_path(picture_id: @picture.id), id: 'comments_link', remote: true


    = render 'comments/form'